baseURL = "https://www.gywang.one/"
relativeURLs = true
languageCode = "en-us"
title = "A place to put my self-reflections"
theme = "ananke"

enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
math = true
color = "#4f46e5"
featured_image = "/images/Shuksan.jpg"

[[params.footer]]
title = "Recent Blog Posts"
recents = "posts"
recentCount = 7

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.social/@Gywang"
username = "gywang"
rel = "me"
